## Environment file to reproduce exercises
name: pgip
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bash_kernel
  - bedtools
  - bokeh
  - ca-certificates
  - csvtk
  # - cyvcf2
  - demesdraw
  - d4tools
  - gatk4
  - gawk
  - jupyter
  - jupyter-cache
  - mosdepth
  - msprime>=1.2
  - pandas
  - pip
  - pyslim
  - python>=3.10
  - python-newick
  # - r-animation
  - r-codetools
  - r-curl
  - r-devtools
  - r-dt
  - r-dygraphs
  - r-formatr
  - r-formattable
  - r-gganimate
  - r-ggiraph
  - r-ggraph
  - r-ggplot2
  - r-gifski
  - r-highcharter
  - r-igraph
  # # - r-irkernel
  # # - r-jsonlite
  - r-kableextra
  - r-leaflet
  - r-networkD3
  - r-magick
  - r-patchwork
  - r-pdftools
  - r-plotly
  # # - r-reactable
  - r-readr
  - r-readxl
  - r-reticulate
  - r-rmarkdown>=2.19
  - r-tidyr
  # # - r-transformr
  - r-viridis
  - samtools
  # # - scikit-learn
  # # - scikit-allel
  - slim>=4.0
  - sgkit
  - tskit>=0.5.0
  # # - tqdm
  # # - yarl
  - pip:
    - cyvcf2
