project:
  type: website
  title: "DDLS Population genomics in practice"
  output-dir: _site
  pre-render:
    - ../scripts/setup-data.sh
    - ../scripts/setup-slides-data.sh
    - ../scripts/setup-exercise-data.sh
    - ../scripts/prepare.py
  render:
    # Root
    - "index.qmd"
    - "contents.qmd"
    - "info.qmd"
    - "precourse.qmd"
    - "references.qmd"
    - "schedule.qmd"
    - "syllabus.qmd"
    # Exercises
    - "exercises/data.qmd"
    - "exercises/index.qmd"
    - "exercises/simulation/index.qmd"
    # Slides
    - "slides/index.qmd"
    - "slides/pgip/index.qmd"
    - "slides/foundations/index.qmd"
    - "slides/simulation/index.qmd"
    - "slides/population_structure/index.qmd"
    # Recipes
    - "recipes/index.qmd"
    - "recipes/slim/index.qmd"
    - "recipes/slides/index.qmd"
    # Exclude
    - "!lectures/*.qmd"
    - "*.ipynb"

metadata-files:
  - _website.yml

bibliography: assets/bibliography.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
from: markdown+emoji

format:
  html:
    theme:
      - assets/css/custom.scss
    toc: true
    embed-resources: true
    date: last-modified
    date-format: "DD-MMM-YYYY"
    lightbox:
      match: auto
  revealjs:
    quarto-required: ">=1.2.475"
    toc: true
    include-after-body: assets/www/logo-hyperlink.html
    toc-depth: 1
    slide-level: 2
    slide-number: true
    preview-links: true
    chalkboard: true
    smaller: false
    highlight-style: gruvbox
    fig-cap-location: top
    fig-align: left
    fig-height: 12
    fig-width: 10
    width: 1280
    height: 720
    margin: 0.1
    date: last-modified
    date-format: "DD-MMM-YYYY"
    navigation-mode: vertical
    institute: NBIS
    reference-location: margin
    template-partials:
      - assets/www/title-slide.html
    title-slide-attributes:
      data-background-image: assets/logos/nbis-scilifelab.svg
      data-background-size: 500px
      data-background-position: top left
    theme:
      - assets/css/custom.scss
    pointer:
      pointerSize: 8
      alwaysVisible: false
      color: red
revealjs-plugins:
  - pointer

execute:
  freeze: auto
  cache: true
  echo: true
  warning: false
  include: true
  autodep: true
  eval: true
  error: true

knitr:
  opts_chunk:
    code-fold: false
    tidy: true
    comment-char: "#>"
    fig-format: svg
    engine.opts:
      dvisvgm.opts: --font-format=woff
      template: assets/www/tikzfig.tex

jupyter:
  kernelspec:
    name: "pgip"
    language: "python"
    display_name: "Python 3"

filters:
  - lightbox
  - fontawesome
