project:
  type: website
  title: "Population genomics in practice"
  output-dir: _site
  pre-render:
    - ../scripts/setup-data.sh
    - ../scripts/setup-slides-data.sh
    - ../scripts/setup-exercise-data.sh
    - ../scripts/prepare.py
  render:
    - "*.qmd"
    - "!lectures/*.qmd"

website:
  title: "Population genomics in practice"
  navbar:
    logo: assets/logos/nbislogo-green.svg
    right:
      - text: "HOME"
        href: "index.qmd"
      - text: "CONTENTS"
        href: "contents.qmd"
      - text: PROGRAM
        href: "program.qmd"
      - text: SCHEDULE
        href: "schedule.qmd"
      - text: ABOUT
        href: "about.qmd"
      - text: SLIDES
        href: "slides/index.qmd"
      - text: EXERCISES
        href: "exercises/index.qmd"
      - icon: "twitter"
        href: "https://twitter.com/NBISwe"
      - icon: "github"
        href: "https://github.com/NBISweden/workshop-pgip"
  page-footer:
    border: false
    left: "2023 [NBIS](about.html) | [GPL-3 License](https://choosealicense.com/licenses/gpl-3.0/)"
    right: "Published with [Quarto](https://quarto.org/) v<?quarto.version?>"
  favicon: assets/logos/nbislogo-green.svg

  sidebar:
    contents:
      - section: Slides
        contents: slides
      - section: Exercises
        contents: exercises
      - section: Code recipes
        contents: recipes

bibliography: assets/bibliography.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl

format:
  html:
    theme:
      - assets/css/custom.scss
    toc: true
    embed-resources: true
    date: last-modified
    date-format: "DD-MMM-YYYY"
    lightbox:
      match: auto
  revealjs:
    quarto-required: ">=1.2.475"
    toc: true
    toc-depth: 1
    slide-level: 2
    slide-number: true
    preview-links: true
    chalkboard: true
    smaller: false
    highlight-style: gruvbox
    fig-cap-location: top
    fig-align: left
    fig-height: 12
    fig-width: 10
    width: 1280
    height: 720
    margin: 0.1
    date: last-modified
    date-format: "DD-MMM-YYYY"
    navigation-mode: vertical
    institute: NBIS
    reference-location: margin
    template-partials:
      - assets/www/title-slide.html
    title-slide-attributes:
      data-background-image: assets/logos/nbis-scilifelab.svg
      data-background-size: 500px
      data-background-position: top left
    theme:
      - assets/css/custom.scss

from: markdown+emoji

execute:
  freeze: auto
  cache: true
  echo: true
  warning: false
  include: true
  autodep: true
  eval: true
  error: true

knitr:
  opts_chunk:
    code-fold: false
    tidy: true
    comment-char: "#>"
    fig-format: svg
    engine.opts:
      dvisvgm.opts: --font-format=woff
      template: assets/www/tikzfig.tex

jupyter:
  kernelspec:
    name: "pgip"
    language: "python"
    display_name: "Python 3"

filters:
  - lightbox
  - fontawesome
